package integration.mindbody;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Provides methods and attributes relating to classes and enrollments.
 *
 * This class was generated by Apache CXF 2.5.6
 * 2015-03-18T23:38:27.851+01:00
 * Generated source version: 2.5.6
 * 
 */
@WebServiceClient(name = "Class_x0020_Service", 
                  wsdlLocation = "https://api.mindbodyonline.com/0_5/ClassService.asmx?wsdl",
                  targetNamespace = "http://clients.mindbodyonline.com/api/0_5") 
public class ClassX0020Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://clients.mindbodyonline.com/api/0_5", "Class_x0020_Service");
    public final static QName ClassX0020ServiceSoap = new QName("http://clients.mindbodyonline.com/api/0_5", "Class_x0020_ServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://api.mindbodyonline.com/0_5/ClassService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClassX0020Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://api.mindbodyonline.com/0_5/ClassService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClassX0020Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClassX0020Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassX0020Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClassX0020Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClassX0020Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClassX0020Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClassX0020ServiceSoap
     */
    @WebEndpoint(name = "Class_x0020_ServiceSoap")
    public ClassX0020ServiceSoap getClassX0020ServiceSoap() {
        return super.getPort(ClassX0020ServiceSoap, ClassX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassX0020ServiceSoap
     */
    @WebEndpoint(name = "Class_x0020_ServiceSoap")
    public ClassX0020ServiceSoap getClassX0020ServiceSoap(WebServiceFeature... features) {
        return super.getPort(ClassX0020ServiceSoap, ClassX0020ServiceSoap.class, features);
    }

}
