package integration.mindbody;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.6
 * 2015-03-18T23:38:27.838+01:00
 * Generated source version: 2.5.6
 * 
 */
@WebService(targetNamespace = "http://clients.mindbodyonline.com/api/0_5", name = "Class_x0020_ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClassX0020ServiceSoap {

    /**
     * Get waitlist entries.
     */
    @WebResult(name = "GetWaitlistEntriesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetWaitlistEntries", action = "http://clients.mindbodyonline.com/api/0_5/GetWaitlistEntries")
    public GetWaitlistEntriesResponse getWaitlistEntries(
        @WebParam(partName = "parameters", name = "GetWaitlistEntries", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetWaitlistEntries parameters
    );

    /**
     * Gets a list of class descriptions.
     */
    @WebResult(name = "GetClassDescriptionsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetClassDescriptions", action = "http://clients.mindbodyonline.com/api/0_5/GetClassDescriptions")
    public GetClassDescriptionsResponse getClassDescriptions(
        @WebParam(partName = "parameters", name = "GetClassDescriptions", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClassDescriptions parameters
    );

    /**
     * Adds clients to enrollments (signup).
     */
    @WebResult(name = "AddClientsToEnrollmentsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "AddClientsToEnrollments", action = "http://clients.mindbodyonline.com/api/0_5/AddClientsToEnrollments")
    public AddClientsToEnrollmentsResponse addClientsToEnrollments(
        @WebParam(partName = "parameters", name = "AddClientsToEnrollments", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddClientsToEnrollments parameters
    );

    /**
     * Gets a list of class schedules.
     */
    @WebResult(name = "GetClassSchedulesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetClassSchedules", action = "http://clients.mindbodyonline.com/api/0_5/GetClassSchedules")
    public GetClassSchedulesResponse getClassSchedules(
        @WebParam(partName = "parameters", name = "GetClassSchedules", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClassSchedules parameters
    );

    /**
     * Adds clients to classes (signup).
     */
    @WebResult(name = "AddClientsToClassesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "AddClientsToClasses", action = "http://clients.mindbodyonline.com/api/0_5/AddClientsToClasses")
    public AddClientsToClassesResponse addClientsToClasses(
        @WebParam(partName = "parameters", name = "AddClientsToClasses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddClientsToClasses parameters
    );

    /**
     * Gets a list of classes.
     */
    @WebResult(name = "GetClassesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetClasses", action = "http://clients.mindbodyonline.com/api/0_5/GetClasses")
    public GetClassesResponse getClasses(
        @WebParam(partName = "parameters", name = "GetClasses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClasses parameters
    );

    /**
     * Removes clients from classes.
     */
    @WebResult(name = "RemoveClientsFromClassesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "RemoveClientsFromClasses", action = "http://clients.mindbodyonline.com/api/0_5/RemoveClientsFromClasses")
    public RemoveClientsFromClassesResponse removeClientsFromClasses(
        @WebParam(partName = "parameters", name = "RemoveClientsFromClasses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        RemoveClientsFromClasses parameters
    );

    /**
     * Gets a list of semesters.
     */
    @WebResult(name = "GetSemestersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetSemesters", action = "http://clients.mindbodyonline.com/api/0_5/GetSemesters")
    public GetSemestersResponse getSemesters(
        @WebParam(partName = "parameters", name = "GetSemesters", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSemesters parameters
    );

    /**
     * Gets a list of enrollments.
     */
    @WebResult(name = "GetEnrollmentsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetEnrollments", action = "http://clients.mindbodyonline.com/api/0_5/GetEnrollments")
    public GetEnrollmentsResponse getEnrollments(
        @WebParam(partName = "parameters", name = "GetEnrollments", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetEnrollments parameters
    );

    /**
     * Update a list of visits.
     */
    @WebResult(name = "UpdateClientVisitsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "UpdateClientVisits", action = "http://clients.mindbodyonline.com/api/0_5/UpdateClientVisits")
    public UpdateClientVisitsResponse updateClientVisits(
        @WebParam(partName = "parameters", name = "UpdateClientVisits", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UpdateClientVisits parameters
    );

    /**
     * Removes client from enrollment waitlist
     */
    @WebResult(name = "RemoveFromWaitlistResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "RemoveFromWaitlist", action = "http://clients.mindbodyonline.com/api/0_5/RemoveFromWaitlist")
    public RemoveFromWaitlistResponse removeFromWaitlist(
        @WebParam(partName = "parameters", name = "RemoveFromWaitlist", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        RemoveFromWaitlist parameters
    );

    /**
     * Gets a class with a list of clients.
     */
    @WebResult(name = "GetClassVisitsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetClassVisits", action = "http://clients.mindbodyonline.com/api/0_5/GetClassVisits")
    public GetClassVisitsResponse getClassVisits(
        @WebParam(partName = "parameters", name = "GetClassVisits", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClassVisits parameters
    );

    /**
     * Gets a list of courses.
     */
    @WebResult(name = "GetCoursesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    @WebMethod(operationName = "GetCourses", action = "http://clients.mindbodyonline.com/api/0_5/GetCourses")
    public GetCoursesResponse getCourses(
        @WebParam(partName = "parameters", name = "GetCourses", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetCourses parameters
    );
}
