package integration.mindbody;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.6
 * 2015-03-18T21:55:47.822+02:00
 * Generated source version: 2.5.6
 * 
 */
@WebService(targetNamespace = "http://clients.mindbodyonline.com/api/0_5", name = "Client_x0020_ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClientX0020ServiceSoap {

    /**
     * Deletes a formula note to a client.
     */
    @WebMethod(operationName = "DeleteClientFormulaNote", action = "http://clients.mindbodyonline.com/api/0_5/DeleteClientFormulaNote")
    @WebResult(name = "DeleteClientFormulaNoteResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public DeleteClientFormulaNoteResponse deleteClientFormulaNote(
        @WebParam(partName = "parameters", name = "DeleteClientFormulaNote", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        DeleteClientFormulaNote parameters
    );

    /**
     * Adds an arrival record for the given client.
     */
    @WebMethod(operationName = "AddArrival", action = "http://clients.mindbodyonline.com/api/0_5/AddArrival")
    @WebResult(name = "AddArrivalResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public AddArrivalResponse addArrival(
        @WebParam(partName = "parameters", name = "AddArrival", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddArrival parameters
    );

    /**
     * Get contact log types for a client.
     */
    @WebMethod(operationName = "GetContactLogTypes", action = "http://clients.mindbodyonline.com/api/0_5/GetContactLogTypes")
    @WebResult(name = "GetContactLogTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetContactLogTypesResponse getContactLogTypes(
        @WebParam(partName = "parameters", name = "GetContactLogTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetContactLogTypes parameters
    );

    /**
     * Gets the active membership for a given client.
     */
    @WebMethod(operationName = "GetActiveClientMemberships", action = "http://clients.mindbodyonline.com/api/0_5/GetActiveClientMemberships")
    @WebResult(name = "GetActiveClientMembershipsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetActiveClientMembershipsResponse getActiveClientMemberships(
        @WebParam(partName = "parameters", name = "GetActiveClientMemberships", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetActiveClientMemberships parameters
    );

    /**
     * Add or update client contact logs.
     */
    @WebMethod(operationName = "AddOrUpdateContactLogs", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateContactLogs")
    @WebResult(name = "AddOrUpdateContactLogsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public AddOrUpdateContactLogsResponse addOrUpdateContactLogs(
        @WebParam(partName = "parameters", name = "AddOrUpdateContactLogs", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateContactLogs parameters
    );

    /**
     * Gets a list of client formula notes.
     */
    @WebMethod(operationName = "GetClientFormulaNotes", action = "http://clients.mindbodyonline.com/api/0_5/GetClientFormulaNotes")
    @WebResult(name = "GetClientFormulaNotesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientFormulaNotesResponse getClientFormulaNotes(
        @WebParam(partName = "parameters", name = "GetClientFormulaNotes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientFormulaNotes parameters
    );

    /**
     * Upload a client document.
     */
    @WebMethod(operationName = "UploadClientDocument", action = "http://clients.mindbodyonline.com/api/0_5/UploadClientDocument")
    @WebResult(name = "UploadClientDocumentResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public UploadClientDocumentResponse uploadClientDocument(
        @WebParam(partName = "parameters", name = "UploadClientDocument", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UploadClientDocument parameters
    );

    /**
     * Sends the user a new password.
     */
    @WebMethod(operationName = "SendUserNewPassword", action = "http://clients.mindbodyonline.com/api/0_5/SendUserNewPassword")
    @WebResult(name = "SendUserNewPasswordResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public SendUserNewPasswordResponse sendUserNewPassword(
        @WebParam(partName = "parameters", name = "SendUserNewPassword", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        SendUserNewPassword parameters
    );

    /**
     * Get visits for a client.
     */
    @WebMethod(operationName = "GetClientVisits", action = "http://clients.mindbodyonline.com/api/0_5/GetClientVisits")
    @WebResult(name = "GetClientVisitsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientVisitsResponse getClientVisits(
        @WebParam(partName = "parameters", name = "GetClientVisits", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientVisits parameters
    );

    /**
     * Get purchases for a client.
     */
    @WebMethod(operationName = "GetClientPurchases", action = "http://clients.mindbodyonline.com/api/0_5/GetClientPurchases")
    @WebResult(name = "GetClientPurchasesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientPurchasesResponse getClientPurchases(
        @WebParam(partName = "parameters", name = "GetClientPurchases", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientPurchases parameters
    );

    /**
     * Gets a list of clients.
     */
    @WebMethod(operationName = "GetClientReferralTypes", action = "http://clients.mindbodyonline.com/api/0_5/GetClientReferralTypes")
    @WebResult(name = "GetClientReferralTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientReferralTypesResponse getClientReferralTypes(
        @WebParam(partName = "parameters", name = "GetClientReferralTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientReferralTypes parameters
    );

    /**
     * Gets account balances for the given clients.
     */
    @WebMethod(operationName = "GetClientAccountBalances", action = "http://clients.mindbodyonline.com/api/0_5/GetClientAccountBalances")
    @WebResult(name = "GetClientAccountBalancesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientAccountBalancesResponse getClientAccountBalances(
        @WebParam(partName = "parameters", name = "GetClientAccountBalances", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientAccountBalances parameters
    );

    /**
     * Gets a list of clients.
     */
    @WebMethod(operationName = "GetClients", action = "http://clients.mindbodyonline.com/api/0_5/GetClients")
    @WebResult(name = "GetClientsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientsResponse getClients(
        @WebParam(partName = "parameters", name = "GetClients", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClients parameters
    );

    /**
     * Validates a username and password. This method returns the associated clients record and a session guid on success.
     */
    @WebMethod(operationName = "ValidateLogin", action = "http://clients.mindbodyonline.com/api/0_5/ValidateLogin")
    @WebResult(name = "ValidateLoginResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public ValidateLoginResponse validateLogin(
        @WebParam(partName = "parameters", name = "ValidateLogin", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        ValidateLogin parameters
    );

    /**
     * Get contact logs for a client.
     */
    @WebMethod(operationName = "GetClientContactLogs", action = "http://clients.mindbodyonline.com/api/0_5/GetClientContactLogs")
    @WebResult(name = "GetClientContactLogsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientContactLogsResponse getClientContactLogs(
        @WebParam(partName = "parameters", name = "GetClientContactLogs", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientContactLogs parameters
    );

    /**
     * Gets a list of currently available client indexes.
     */
    @WebMethod(operationName = "GetClientIndexes", action = "http://clients.mindbodyonline.com/api/0_5/GetClientIndexes")
    @WebResult(name = "GetClientIndexesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientIndexesResponse getClientIndexes(
        @WebParam(partName = "parameters", name = "GetClientIndexes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientIndexes parameters
    );

    /**
     * Updates a client service for a given client.
     */
    @WebMethod(operationName = "UpdateClientServices", action = "http://clients.mindbodyonline.com/api/0_5/UpdateClientServices")
    @WebResult(name = "UpdateClientServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public UpdateClientServicesResponse updateClientServices(
        @WebParam(partName = "parameters", name = "UpdateClientServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UpdateClientServices parameters
    );

    /**
     * Updates a client service for a given client.
     */
    @WebMethod(operationName = "GetRequiredClientFields", action = "http://clients.mindbodyonline.com/api/0_5/GetRequiredClientFields")
    @WebResult(name = "GetRequiredClientFieldsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetRequiredClientFieldsResponse getRequiredClientFields(
        @WebParam(partName = "parameters", name = "GetRequiredClientFields", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetRequiredClientFields parameters
    );

    /**
     * Gets a client service for a given client.
     */
    @WebMethod(operationName = "GetClientServices", action = "http://clients.mindbodyonline.com/api/0_5/GetClientServices")
    @WebResult(name = "GetClientServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientServicesResponse getClientServices(
        @WebParam(partName = "parameters", name = "GetClientServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientServices parameters
    );

    /**
     * Gets a list of currently available client indexes.
     */
    @WebMethod(operationName = "GetCustomClientFields", action = "http://clients.mindbodyonline.com/api/0_5/GetCustomClientFields")
    @WebResult(name = "GetCustomClientFieldsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetCustomClientFieldsResponse getCustomClientFields(
        @WebParam(partName = "parameters", name = "GetCustomClientFields", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetCustomClientFields parameters
    );

    /**
     * Adds or updates information for a list of clients.
     */
    @WebMethod(operationName = "AddOrUpdateClients", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateClients")
    @WebResult(name = "AddOrUpdateClientsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public AddOrUpdateClientsResponse addOrUpdateClients(
        @WebParam(partName = "parameters", name = "AddOrUpdateClients", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateClients parameters
    );

    /**
     * Gets a list of contracts for a given client.
     */
    @WebMethod(operationName = "GetClientContracts", action = "http://clients.mindbodyonline.com/api/0_5/GetClientContracts")
    @WebResult(name = "GetClientContractsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientContractsResponse getClientContracts(
        @WebParam(partName = "parameters", name = "GetClientContracts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientContracts parameters
    );

    /**
     * Get visits for a client.
     */
    @WebMethod(operationName = "GetClientSchedule", action = "http://clients.mindbodyonline.com/api/0_5/GetClientSchedule")
    @WebResult(name = "GetClientScheduleResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public GetClientScheduleResponse getClientSchedule(
        @WebParam(partName = "parameters", name = "GetClientSchedule", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClientSchedule parameters
    );

    /**
     * Adds a formula note to a client.
     */
    @WebMethod(operationName = "AddClientFormulaNote", action = "http://clients.mindbodyonline.com/api/0_5/AddClientFormulaNote")
    @WebResult(name = "AddClientFormulaNoteResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", partName = "parameters")
    public AddClientFormulaNoteResponse addClientFormulaNote(
        @WebParam(partName = "parameters", name = "AddClientFormulaNote", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddClientFormulaNote parameters
    );
}
