
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package integration.mindbody;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.6
 * 2015-03-18T21:55:47.782+02:00
 * Generated source version: 2.5.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "Client_x0020_Service",
                      portName = "Client_x0020_ServiceSoap",
                      targetNamespace = "http://clients.mindbodyonline.com/api/0_5",
                      wsdlLocation = "https://api.mindbodyonline.com/0_5/ClientService.asmx?wsdl",
                      endpointInterface = "integration.mindbody.ClientX0020ServiceSoap")
                      
public class ClientX0020ServiceSoapImpl implements ClientX0020ServiceSoap {

    private static final Logger LOG = Logger.getLogger(ClientX0020ServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#deleteClientFormulaNote(integration.mindbody.DeleteClientFormulaNote  parameters )*
     */
    public integration.mindbody.DeleteClientFormulaNoteResponse deleteClientFormulaNote(DeleteClientFormulaNote parameters) { 
        LOG.info("Executing operation deleteClientFormulaNote");
        System.out.println(parameters);
        try {
            integration.mindbody.DeleteClientFormulaNoteResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#addArrival(integration.mindbody.AddArrival  parameters )*
     */
    public integration.mindbody.AddArrivalResponse addArrival(AddArrival parameters) { 
        LOG.info("Executing operation addArrival");
        System.out.println(parameters);
        try {
            integration.mindbody.AddArrivalResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getContactLogTypes(integration.mindbody.GetContactLogTypes  parameters )*
     */
    public integration.mindbody.GetContactLogTypesResponse getContactLogTypes(GetContactLogTypes parameters) { 
        LOG.info("Executing operation getContactLogTypes");
        System.out.println(parameters);
        try {
            integration.mindbody.GetContactLogTypesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getActiveClientMemberships(integration.mindbody.GetActiveClientMemberships  parameters )*
     */
    public integration.mindbody.GetActiveClientMembershipsResponse getActiveClientMemberships(GetActiveClientMemberships parameters) { 
        LOG.info("Executing operation getActiveClientMemberships");
        System.out.println(parameters);
        try {
            integration.mindbody.GetActiveClientMembershipsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#addOrUpdateContactLogs(integration.mindbody.AddOrUpdateContactLogs  parameters )*
     */
    public integration.mindbody.AddOrUpdateContactLogsResponse addOrUpdateContactLogs(AddOrUpdateContactLogs parameters) { 
        LOG.info("Executing operation addOrUpdateContactLogs");
        System.out.println(parameters);
        try {
            integration.mindbody.AddOrUpdateContactLogsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientFormulaNotes(integration.mindbody.GetClientFormulaNotes  parameters )*
     */
    public integration.mindbody.GetClientFormulaNotesResponse getClientFormulaNotes(GetClientFormulaNotes parameters) { 
        LOG.info("Executing operation getClientFormulaNotes");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientFormulaNotesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#uploadClientDocument(integration.mindbody.UploadClientDocument  parameters )*
     */
    public integration.mindbody.UploadClientDocumentResponse uploadClientDocument(UploadClientDocument parameters) { 
        LOG.info("Executing operation uploadClientDocument");
        System.out.println(parameters);
        try {
            integration.mindbody.UploadClientDocumentResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#sendUserNewPassword(integration.mindbody.SendUserNewPassword  parameters )*
     */
    public integration.mindbody.SendUserNewPasswordResponse sendUserNewPassword(SendUserNewPassword parameters) { 
        LOG.info("Executing operation sendUserNewPassword");
        System.out.println(parameters);
        try {
            integration.mindbody.SendUserNewPasswordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientVisits(integration.mindbody.GetClientVisits  parameters )*
     */
    public integration.mindbody.GetClientVisitsResponse getClientVisits(GetClientVisits parameters) { 
        LOG.info("Executing operation getClientVisits");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientVisitsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientPurchases(integration.mindbody.GetClientPurchases  parameters )*
     */
    public integration.mindbody.GetClientPurchasesResponse getClientPurchases(GetClientPurchases parameters) { 
        LOG.info("Executing operation getClientPurchases");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientPurchasesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientReferralTypes(integration.mindbody.GetClientReferralTypes  parameters )*
     */
    public integration.mindbody.GetClientReferralTypesResponse getClientReferralTypes(GetClientReferralTypes parameters) { 
        LOG.info("Executing operation getClientReferralTypes");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientReferralTypesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientAccountBalances(integration.mindbody.GetClientAccountBalances  parameters )*
     */
    public integration.mindbody.GetClientAccountBalancesResponse getClientAccountBalances(GetClientAccountBalances parameters) { 
        LOG.info("Executing operation getClientAccountBalances");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientAccountBalancesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClients(integration.mindbody.GetClients  parameters )*
     */
    public integration.mindbody.GetClientsResponse getClients(GetClients parameters) { 
        LOG.info("Executing operation getClients");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#validateLogin(integration.mindbody.ValidateLogin  parameters )*
     */
    public integration.mindbody.ValidateLoginResponse validateLogin(ValidateLogin parameters) { 
        LOG.info("Executing operation validateLogin");
        System.out.println(parameters);
        try {
            integration.mindbody.ValidateLoginResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientContactLogs(integration.mindbody.GetClientContactLogs  parameters )*
     */
    public integration.mindbody.GetClientContactLogsResponse getClientContactLogs(GetClientContactLogs parameters) { 
        LOG.info("Executing operation getClientContactLogs");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientContactLogsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientIndexes(integration.mindbody.GetClientIndexes  parameters )*
     */
    public integration.mindbody.GetClientIndexesResponse getClientIndexes(GetClientIndexes parameters) { 
        LOG.info("Executing operation getClientIndexes");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientIndexesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#updateClientServices(integration.mindbody.UpdateClientServices  parameters )*
     */
    public integration.mindbody.UpdateClientServicesResponse updateClientServices(UpdateClientServices parameters) { 
        LOG.info("Executing operation updateClientServices");
        System.out.println(parameters);
        try {
            integration.mindbody.UpdateClientServicesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getRequiredClientFields(integration.mindbody.GetRequiredClientFields  parameters )*
     */
    public integration.mindbody.GetRequiredClientFieldsResponse getRequiredClientFields(GetRequiredClientFields parameters) { 
        LOG.info("Executing operation getRequiredClientFields");
        System.out.println(parameters);
        try {
            integration.mindbody.GetRequiredClientFieldsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientServices(integration.mindbody.GetClientServices  parameters )*
     */
    public integration.mindbody.GetClientServicesResponse getClientServices(GetClientServices parameters) { 
        LOG.info("Executing operation getClientServices");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientServicesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getCustomClientFields(integration.mindbody.GetCustomClientFields  parameters )*
     */
    public integration.mindbody.GetCustomClientFieldsResponse getCustomClientFields(GetCustomClientFields parameters) { 
        LOG.info("Executing operation getCustomClientFields");
        System.out.println(parameters);
        try {
            integration.mindbody.GetCustomClientFieldsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#addOrUpdateClients(integration.mindbody.AddOrUpdateClients  parameters )*
     */
    public integration.mindbody.AddOrUpdateClientsResponse addOrUpdateClients(AddOrUpdateClients parameters) { 
        LOG.info("Executing operation addOrUpdateClients");
        System.out.println(parameters);
        try {
            integration.mindbody.AddOrUpdateClientsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientContracts(integration.mindbody.GetClientContracts  parameters )*
     */
    public integration.mindbody.GetClientContractsResponse getClientContracts(GetClientContracts parameters) { 
        LOG.info("Executing operation getClientContracts");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientContractsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#getClientSchedule(integration.mindbody.GetClientSchedule  parameters )*
     */
    public integration.mindbody.GetClientScheduleResponse getClientSchedule(GetClientSchedule parameters) { 
        LOG.info("Executing operation getClientSchedule");
        System.out.println(parameters);
        try {
            integration.mindbody.GetClientScheduleResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see integration.mindbody.ClientX0020ServiceSoap#addClientFormulaNote(integration.mindbody.AddClientFormulaNote  parameters )*
     */
    public integration.mindbody.AddClientFormulaNoteResponse addClientFormulaNote(AddClientFormulaNote parameters) { 
        LOG.info("Executing operation addClientFormulaNote");
        System.out.println(parameters);
        try {
            integration.mindbody.AddClientFormulaNoteResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
